version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: driver-redis
    ports:
      - "6379:6379"

  driver-service:
    build: .
    container_name: driver-service
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "8082:8082"

